### ISSUE TITLE
Glyph codes get rewritten when exporting font

### ISSUE THREAD

**Issue by matildaaistre** [fontello/fontello#727]
As a designer I have used Fontello for about a year now at the company I'm working for and it's been great. We use an icon font in our product to display icons in buttons and other components. We also have some legacy glyph codes from another tool that was used before.

**Describe the bug**
Since a couple of weeks back it seems that the glyph codes get's rewritten when exporting the font after updating it with new icons etc. and our production environment breaks. It would be nice to not have to go through them manually and update every single one.

**To Reproduce**
1. Upload an SVG font (before this bug I could also add my config.json file and it would work, but now that also shows the wrong glyph codes even if my SVG font file shows the right ones)
2. Look at one of the glyph codes
3. Export the font and upload it again
4. Look at the same one and see that it has changed

**Expected behavior**
The export to keep the same glyph codes as before

**Screenshots**
When I upload the font:
<img width="673" alt="Screenshot 2020-12-12 at 13 30 07" src="https://user-images.githubusercontent.com/75848631/101983978-b2e79780-3c7e-11eb-9caf-661c456daa49.png">

And export and upload it again and look at the same one:
<img width="661" alt="Screenshot 2020-12-12 at 13 30 38" src="https://user-images.githubusercontent.com/75848631/101983988-bc70ff80-3c7e-11eb-81d7-cab1f072128b.png">

**OS/Browser**
 - OS: OSX Mojave (10.14.6)
 - Browser: Chrome (v87.0.4280.88), Safari (v14.0.1) and Firefox (v83.0)

**Font/config**
[commonui-icons.zip](https://github.com/fontello/fontello/files/5683065/commonui-icons.zip)

**Comment by puzrin** [comment]
Try to change encoding to "unicode" in settings.

But remapping should never happen on config import, you are right.

**Comment by matildaaistre** [comment]
Just tested it, and the config is working again and therefore also the unicode setting which I forgot about. Thanks!

**Comment by rlidwka** [comment]
Fixed by https://github.com/fontello/fontello/commit/d5a2eed49362b19140d079d8229553d8373bd22d, it should work now.

**Comment by Kapusch** [comment]
I've encountered the described issue many times, and I can see this is now working very well when importing my config file, thank you @rlidwka !

**Comment by cornae** [comment]
Remapping still happens to me in Safari, Chrome and Firefox. I have a mix of custom icons and standard icons. When I import my library with the json file, add and extra icon and then download the new library, some existing icons are remapped. It also happens that the newly added icon gets a different (existing) icon instead of the selected one on the fontello website.

**Comment by puzrin** [comment]
@cornae please create detailed info (with files) how to reproduce in FF/Chrome.

**Comment by cornae** [comment]
I'm trying the same procedure as I did several times just a few hours ago, but with a different outcome this time. I also had different outcomes between different browsers. But now I get the same outcome across Safari, Firefox and Chrome. So I'm afraid this is not going to help much. But what I did was the following.

1. Import the json file of my existing library
2. Select an extra icon called 'layers' from Iconic
3. Export (Encoding is on private use area)

The only thing that has changed between when things failed and now is that I've switched to Unicode and back to Private use area again.

The problem a few hours ago was that the newly added layers icon would get the Unicode E801. Which is the code the heart icon already had. But in my new download it gives the layers icon gets the code E91A. I cannot explain why I'm getting different results this time. I've experienced the issue since December.

I'm on macOS 11.2.1 (20D74)

[before import.zip](https://github.com/fontello/fontello/files/6044037/before.import.zip)

**Comment by cornae** [comment]
I retrieved an export of some hours ago in which icon-layers received the same unicode as icon-heart.

[fontello-1b4a1eb9.zip](https://github.com/fontello/fontello/files/6044139/fontello-1b4a1eb9.zip)

**Comment by puzrin** [comment]
@cornae we can investigate only concrete reproducible cases, sorry.

**Comment by cornae** [comment]
I understand. Part of the problem is that it seems erratic. The only thing I have is the ZIP file with the different outcome.

**Comment by puzrin** [comment]
Closing because initial issue was solved. When new reproducible scenario found - create a new issue.
